#:schema https://fnox.jdx.dev/schema.json

if_missing = "error"

[providers]
keychain = { type = "keychain", service = "polymarket-client-sdk-ext" }
pass = { type = "password-store", prefix = "polymarket-client-sdk-ext/" }
